modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "duckling"
version = "${version}"
displayName = "Duckling"
authors = "Artist - Frogipher, Dev - ThatGravyBoat"
description = """
Adds some quacky little friends!
Quacking Sounds - freesoundslibrary.com/duck-quack/
Note: Sounds were edited out and pitched up and down."""

[[dependencies.duckling]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.duckling]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.duckling]]
    modId = "geckolib"
    mandatory = true
    versionRange = "[4,)"
    ordering = "NONE"
    side = "BOTH"